# Grundlegendes zu Python

Ein superkurzer Crashkurs.

Hier versuche ich einmal grundlegende Operationen für diese kleine Einführung zu vermitteln. Starten werden wir damit, dass Python so funktioniert, dass es einfach eine Liste von Befehlen von oben nach unten abarbeitet. Im einfachsten Fall ist Python ein Taschenrechner.

In [1]:
5 + 7

12

Verschiedene mathematische Operationen sind hierbei möglich. 

* Addition: +
* Subtraktion: -
* Multiplikation: 
* Division: /
* Division mit Rest: //
* Rest der Division mit Rest: %
* Potenzen: **

Außerdem können die Werte von Operationen Variablen zugeordnet werden. So kann ich zum Beispiel Ergebnisse für später speichern. Wichtig ist, dass die Variablen möglichst deskriptive Namen haben, damit man den Überblick behält. Außerdem müssen die Variablennamen mit einem Buchstaben starten (also keinem Sonderzeichen oder einer Zahl).

In [5]:
a = 5
b = 7
a + b

12

Variablen können aber z.B. auch eine Kommazahl sein sogenannte `floats` (ganze Zahlen sind integers oder `int`) oder Zeichenketten (gekennzeichnet durch " " oder ' '). Manche dieser Variablentypen sind miteinander Kompatibel, andere nicht.

In [6]:
a = 5.5
b = "8"
(
    a + b
)  # Sollte einen Fehler produzieren, da 8 eine Zeichenkette darstellt, obwohl sie eine Ziffer abbildet

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [7]:
a = 5
b = "Hund"
a + b  # Auch hier sollte ein Fehler produziert werden.

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [14]:
a = 5.5
b = 8
a + b

13.5

Wir können aber auch andere Befehle nutzen. Innerhalb von Python gibt es eine Vielzahl davon: Einige um zu rechnen, andere um Texte zu analysieren. Der wohl einfachste ist der `print()` Befehl, der einfach eine Variable ausgibt.

In [15]:
print(b)

8


Man kann mit einem sogenannten f-string auch noch etwas dazu schreiben. Das könnte so aussehen.

In [16]:
print(f"Die Variable b enthält den Wert {b}.")

Die Variable b enthält den Wert 8.


In einem f-string wird vor " " oder ' ' ein f geschrieben und alles in geschwiffenen Klammern {} kann noch Python Code enthalten, der ausgeführt wird.

Es gibt aber auch Möglichkeiten mehrere Daten in einer Variable zu speichern, z.B. Listen.

In [17]:
a = [1, 2, 3, 4, 5, 6]

oder Tuple:

In [18]:
b = (1, 2, 3, 4, 5)

Beide könnten auch unterschiedliche Arten von Daten enthalten:

In [20]:
c = ["a", 4, 8.6, "c"]
d = ("a", 4, 8.6, "c")

Auf die einzelnen Elemente kann zugreifen, mit einem sogenannten Index. Der Index ergibt sich quasi indem man von vorne nach hinten bei 0 beginnend durchzählt.

In [21]:
a[0]

1

In [23]:
b[3]

4

Man kann auch mehrere auswählen 0:3 (das erste bis zum dritten Element, das vierte also die 3 wird ausgeschlossen), das wir manchmal als :3 abgekürzt oder jedes zweite 2:7:2 (vom dritten Element bis zum siebten jedes zweite) oder man kann von hinten zu zählen beginnen -1

In [27]:
print(a[0:3])
print(a[:3])
print(a[2:7:2])
print(a[-1])

[1, 2, 3]
[1, 2, 3]
[3, 5]
6


Mit Modulen wie numpy oder pandas lassen sich Rechnungen noch effizienter durchführen. Dazu importiere ich unten Numpy unter dem Namen np, damit ich es nutzen kann und erstelle anschließend eine Matrix mit Werten von 1-12.

In [31]:
import numpy as np

a = np.arange(
    1, 13
)  # kreiert einen numpy.array (ein weiterer Datentyp ähnlich einer Liste), der mit den Zahlen im range von 1 - 13 (exkludiert) gefüllt wird.
print(a), print(" ")  # der zweite Printbefehl erzeugt eine Leerzeile
a = a.reshape(
    4, 3
)  # ordnet den numpy.array neu an, sodass er 4 Zeilen und 3 Spalten hat. Die Regel ist immer Zeilen vor Spalten
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Auch mit numpy.arrays lässt sich rechnen:

In [33]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [34]:
a + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [36]:
a % 7

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [40]:
b = np.arange(12, 24)
b = b.reshape(4, 3)
print(b), print(" ")
a + b

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
 


array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

Numpy erlaubt auch mit den arrays spezielle Operationen durchzuführen z.B. den Mittelwert zu bilden.

In [41]:
# Gesamtmittelwert
a.mean()

6.5

In [42]:
# Mittelwert der Reihen
a.mean(
    axis=0
)  # Reihen vor Spalten und wir beginnen das Zählen bei 0, daher sind die Reihen die 0. Dimension

array([5.5, 6.5, 7.5])

In [43]:
# Mittelwert der Spalten
a.mean(axis=1)

array([ 2.,  5.,  8., 11.])

Q: Wiederhole die Rechnungen zum Mittelwert mit dem Array b

Pandas benutzt man vor allem, um mit Tabellen zu arbeiten. Hierfür laden wir einmal eine mitgebrachte Tabelle.

In [44]:
import pandas as pd

penguins = pd.read_csv("./penguins_classification.csv")

Um einen Überblick über die Tabelle zu bekommen, kann man `.head()` benutzen

In [45]:
penguins.head()

Culmen Length (mm)  Culmen Depth (mm) Species
0                39.1               18.7  Adelie
1                39.5               17.4  Adelie
2                40.3               18.0  Adelie
3                36.7               19.3  Adelie
4                39.3               20.6  Adelie

Wenn wir einzelne Spalten auswählen wollen, dann können wir diese mit ihrem Spaltennamen auswählen.

In [47]:
penguins["Culmen Length (mm)"]

0      39.1
1      39.5
2      40.3
3      36.7
4      39.3
       ... 
337    55.8
338    43.5
339    49.6
340    50.8
341    50.2
Name: Culmen Length (mm), Length: 342, dtype: float64

Weiteres Grundlegendes findet ihr in 01_KorrelationenTTest.